export enum RouteString {
    main = "/",
    budget = "/budget",
    budgetCreate = "/budget_create",
    budgetEdit = "/budget_edit",
    income = "/income",
    incomeCreate = "/income_create",
    incomeEdit = "/income_edit",
    expenses = "/expense",
    expensesCreate = "/expense_create",
    expensesEdit = "/expense_edit",
    login = "/login",
    signup = "/signup",
    logout = "/logout",
    notFound = "/404",
}